PCI: keystone: Fix compilation error when CONFIG_PCI=n
Fix the following compilation error when CONFIG_PCI is disabled
and PCI_KEYSTONE_EP is enabled.

error: implicit declaration of function ‘pci_match_id’
error: implicit declaration of function ‘pcie_get_readrq’
error: implicit declaration of function ‘pcie_set_readrq’
error: implicit declaration of function ‘devm_pci_remap_cfg_resource’

Fix it by adding ks_pcie_quirk() within #ifdef CONFIG_PCI since it is
specific to RC mode, replacing devm_pci_remap_cfg_resource() with
devm_ioremap_resource() in ks_pcie_probe and adding a stub function
devm_pci_remap_cfg_resource() in pci.h to be used when CONFIG_PCI is
not set.

Signed-off-by: Kishon Vijay Abraham I <kishon@ti.com>
Reported-by: Bin Liu <b-liu@ti.com>
Signed-off-by: Sekhar Nori <nsekhar@ti.com>