memory: omap-gpmc: select GPIOLIB_IRQCHIP
OMAP GPMC driver uses irqchip in gpiolib but
does not select GPIOLIB_IRQCHIP. This can lead
to errors like below in randconfig builds.

  CC      drivers/memory/omap-gpmc.o
drivers/memory/omap-gpmc.c: In function ‘gpmc_handle_irq’:
drivers/memory/omap-gpmc.c:2007:43: error: ‘struct gpio_chip’ has no member named ‘irqdomain’
    virq = irq_find_mapping(gpmc->gpio_chip.irqdomain,
                                           ^
drivers/memory/omap-gpmc.c: In function ‘gpmc_gpio_init’:
drivers/memory/omap-gpmc.c:2088:2: error: implicit declaration of function ‘gpiochip_irqchip_add’ [-Werror=implicit-function-declaration]
  ret = gpiochip_irqchip_add(&gpmc->gpio_chip, &gpmc->irq_chip, 0,
  ^

Fixes: 8ec7ee22749e ("memory: omap-gpmc: Add irqchip support to the gpiochip")
Signed-off-by: Sekhar Nori <nsekhar@ti.com>
Signed-off-by: Kishon Vijay Abraham I <kishon@ti.com>