drm/tilcdc: fix build error due to pinctrl
Fix this error:

drivers/gpu/drm/tilcdc/tilcdc_drv.c:552:2: error: implicit declaration of function ‘pinctrl_pm_select_sleep_state’ [-Werror=implicit-function-declaration]
  pinctrl_pm_select_sleep_state(dev);

Fixes: 6d4f88b9843d ("drm/tilcdc: adopt pinctrl support")

Signed-off-by: Sekhar Nori <nsekhar@ti.com>
Signed-off-by: Darren Etheridge <detheridge@ti.com>