spi: spi-omap2-mcspi: dma_rx_cookie variable uninitialize
dma_cookie_t dma_rx_cookie variable in omap2_mcspi_rx_dma introduce in
a previous commit was not initialized.
So when you build with -Werror,-Wsometimes-uninitialized we have this
error:

drivers/spi/spi-omap2-mcspi.c:478:6: error: variable 'dma_rx_cookie' is
used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized
]
        if (tx) {
            ^~                                                                                                                                                                                 drivers/spi/spi-omap2-mcspi.c:494:55:note: uninitialized use occurs here
                dma_status = dmaengine_tx_status(mcspi_dma->dma_rx,
dma_rx_cookie,
^~~~~~~~~~~~~
drivers/spi/spi-omap2-mcspi.c:478:2:note: remove the 'if'
if its condition is always true
        if (tx) {
        ^~~~~~~~
drivers/spi/spi-omap2-mcspi.c:417:28:note: initialize the variable
'dma_rx_cookie' to silence this warning
        dma_cookie_t dma_rx_cookie;
                                  ^
                                   = 0

Initialize dma_cookie to fix build issue.

Fixes: 907e39b5b1e1 ("spi: spi-omap2-mcspi: Use EOW interrupt for completion when DMA enabled")
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>