ARM: OMAP2+: Add am33xx_pm_deinit stub for !CONFIG_CPU_IDLE
Add an empty stub for builds done with !CONFIG_CPU_IDLE, otherwise
build will fail with error:

arch/arm/mach-omap2/pm33xx-core.c: In function ‘am33xx_pm_deinit’:
arch/arm/mach-omap2/pm33xx-core.c:131:2: error: implicit declaration of
function ‘am33xx_idle_deinit’ [-Werror=implicit-function-declaration]
  am33xx_idle_deinit();

Fixes: 5e1e88c82b54 ("ARM: OMAP2+: Add am33xx_pm_deinit to disable cpuidle")
Reported-by: Dan Murphy <dmurphy@ti.com>
Signed-off-by: Dave Gerlach <d-gerlach@ti.com>