rpmsg-kdrv: eth-switch: use tabs instead of spaces for indentation
Fix this checkpatch error:

ERROR: code indent should use tabs where possible

Signed-off-by: Grygorii Strashko <grygorii.strashko@ti.com>
Signed-off-by: Sekhar Nori <nsekhar@ti.com>