ARM: OMAP2+: NAND: Fix for NAND module build support
NAND driver fails to build as module with following error.

ERROR: "gpmc_calculate_ecc" [drivers/mtd/nand/omap2.ko] undefined!
ERROR: "gpmc_enable_hwecc" [drivers/mtd/nand/omap2.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2

This fixes the same by using EXPORT_SYMBOL.

Note:
This patch was actually reverted before moving gpmc from
postcore_initcall to module_platform_driver. Since moving is completes,
we need this patch.

Signed-off-by: Philip, Avinash <avinashphilip@ti.com>
Signed-off-by: Vaibhav Hiremath <hvaibhav@ti.com>