fix i2c build errors
It seems to be a merge error in the omap tree that causes the following
build errors with e.g. ateb9200_defconfig:

<--  snip  -->

...
  MODPOST 93 modules
ERROR: "__i2c_board_list" [drivers/i2c/i2c-core.ko] undefined!
ERROR: "__i2c_board_lock" [drivers/i2c/i2c-core.ko] undefined!
ERROR: "__i2c_first_dynamic_bus_num" [drivers/i2c/i2c-core.ko] undefined!
make[2]: *** [__modpost] Error 1

<--  snip  -->

Signed-off-by: Adrian Bunk <adrian.bunk@movial.fi>
Signed-off-by: Tony Lindgren <tony@atomide.com>