OMAP2 STI: fix build breakage
n800_defconfig no longer builds after commit
8423eaf634aa187e2ab3cd1018ea0f2f7d31148a; fix.

  CC      drivers/misc/sti/sti-netlink.o
drivers/misc/sti/sti-netlink.c: In function 'sti_netlink_receive_msg':
drivers/misc/sti/sti-netlink.c:84: error: expected expression before 'int'
drivers/misc/sti/sti-netlink.c:91: error: 'len' undeclared (first use in this function)
drivers/misc/sti/sti-netlink.c:91: error: (Each undeclared identifier is reported only once
drivers/misc/sti/sti-netlink.c:91: error: for each function it appears in.)

Signed-off-by: Paul Walmsley <paul@pwsan.com>
Cc: Roman Tereshenkov <roman.tereshonkov@nokia.com>
Cc: Felipe Balbi <felipe.balbi@nokia.com>
Cc: Tony Lindgren <tony@atomide.com>
Signed-off-by: Tony Lindgren <tony@atomide.com>