firmware: Fix build error when TI_SCI_PROTOCOL=m
The following build error happens when TI_SCI_PROTOCOL=m

drivers/firmware/ti_sci.c:512:29: error: redefinition of 'ti_sci_get_handle'
 const struct ti_sci_handle *ti_sci_get_handle(struct device *dev)

Fix it by checking for IS_ENABLED(CONFIG_TI_SCI_PROTOCOL).

Fixes: 96671d9f698b0 ("firmware: Add support for TI System Control Interface (TI-SCI) protocol")
Reported-by: Dan Murphy <dmurphy@ti.com>
Signed-off-by: Lokesh Vutla <lokeshvutla@ti.com>
Acked-by: Nishanth Menon <nm@ti.com>
Tested-by: Dan Murphy <dmurphy@ti.com>