HACK: media: zoran: Fix kbuild test robot error on x86_64 build
kbuild test robot reported the following:

All errors (new ones prefixed by >>):

   In file included from drivers/media/pci/zoran/zoran_procfs.c:45:0:
>> drivers/media/pci/zoran/zoran.h:64:5: error: #error "Too many video
   frame buffers to handle"
    #   error   "Too many video frame buffers to handle"
        ^~~~~
   In file included from drivers/media/pci/zoran/zoran_procfs.c:45:0:
>> drivers/media/pci/zoran/zoran.h:326:15: error: 'V4L_MAX_FRAME'
   undeclared here (not in a function); did you mean 'V4L_MASK_FRAME'?
     int v4l_pend[V4L_MAX_FRAME];
                  ^~~~~~~~~~~~~
                  V4L_MASK_FRAME

Since we have a HACK to increase the VIDEO_MAX_FRAME to 128 see
commit 88309bacfe49 ("HACK: UAPI: Increasing
VIDEO_MAX_FRAME/VB2_MAX_FRAME to 128.")

We also need to HACK this very old driver to make the synthetic build
succeed on an architecture we don't normally support.

Signed-off-by: Benoit Parrot <bparrot@ti.com>
Acked-by: Tomi Valkeinen <tomi.valkeinen@ti.com>