net: ethernet: ti: use mac_addr variable instead of a pointer
When we use clang to build with -Wall and -Werror flags we see this issue:

drivers/net/ethernet/ti/j721e-cpsw-virt-mac.c:1292:36: error: variable
'mac_addr' is uninitialized when used here [-Werror,-Wuninitialized]
        ret = of_get_mac_address(port_np, mac_addr);
                                          ^~~~~~~~
Use variable instead of a pointer.

Fixes: 7b0e83633301 ("net: ethernet: ti: introduce j721e virt cpsw-nuss mac driver")
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>