TI-Integration: Fix build break after rpmsg merge
There was an API change that occured in the power
management domain branch that was not available on the
rpmsg domain branch.  This caused the following error

drivers/remoteproc/wkup_m3_rproc.c: In function ‘wkup_m3_copy_aux_data’:
drivers/remoteproc/wkup_m3_rproc.c:240:12: error: too few arguments to function ‘rproc_da_to_va’
In file included from drivers/remoteproc/wkup_m3_rproc.c:34:0:
drivers/remoteproc/remoteproc_internal.h:71:7: note: declared here

Therefore per the rpmsg maintainer there needed to be 0 passed in as the
last argument.  This patch makes that change

Reported-by: Suman Anna <s-anna@ti.com>
Signed-off-by: Dan Murphy <DMurphy@ti.com>