ARM: fix build break due to typo in cacheflush.h
commit 9d85ac1e6 introduced a small typo. This causes the build
to break when CONFIG_CPU_V7 is set and CONFIG_CPU_V6 and
CONFIG_SMP_ON_UP are not. (log below)

  CC      init/main.o
In file included from include/linux/highmem.h:9,
                 from include/linux/pagemap.h:10,
                 from include/linux/mempolicy.h:70,
                 from init/main.c:50:
arch/arm/include/asm/cacheflush.h: In function '__flush_icache_all':
arch/arm/include/asm/cacheflush.h:332: error: implicit declaration of function '__flush_icache_preferred'
make[1]: *** [init/main.o] Error 1
make: *** [init] Error 2

Signed-off-by: Anand Gadiyar <gadiyar@ti.com>
Cc: Tony Lindgren <tony@atomide.com>
Signed-off-by: Tony Lindgren <tony@atomide.com>