omap: Fix compile for early_param and omap_smc1
Commit 2b0d8c251b8876d530a6bf671eb5425838fa698a changed ARM to use
the common early_param code. Fix compile for omaps accordingly.

Commit d309427e792ea750cdd312e7a92cf6047ae44962 added support for
CACHE_L2X0, this however breaks multi-omap builds for V6 because of
dsb and smc. The proper fix is to separate omap_smc1 into a separate
.S file and compile it with -Wa,-march=armv7-a flags.

Also for some reason touchbook produces a compile error

error: __setup_str_early_touchbook_revision causes a section type conflict

Unless ehci_pdata is set to __initdata instead of __initconst.
No idea yet why this happens only on touchbook.

Not-Yet-Signed-off-by: Tony Lindgren <tony@atomide.com>