serial: 8250/keystone: fix building with SERIAL_8250=m
The Keystone 8250 driver has a 'bool' Kconfig symbol, but that
breaks when SERIAL_8250 is a loadable module:

ERROR: "keystone_serial8250_init" [drivers/tty/serial/8250/8250.ko] undefined!

This changes the symbol to a 'tristate', so the dependency on
SERIAL_8250 also works when that is set to 'm'.

Signed-off-by: Sekhar Nori <nsekhar@ti.com>