drivers: power: build when voltage domain is selected as well
drivers/power is not built when CONFIG_POWER_SUPPLY is disabled.

This does not allow voltage domain driver to get built as well, since
voltage domain drivers are in drivers/power/voltdm. So force power
directory to be entered for build when voltagedomain is defined as well.

This fixes the following build error with randconfig:

drivers/built-in.o: In function `cpufreq_exit':
linux/drivers/cpufreq/cpufreq-voltdm.c:217: undefined reference to `of_pm_voltdm_notifier_unregister'
drivers/built-in.o: In function `cpufreq_init':
linux/drivers/cpufreq/cpufreq-voltdm.c:165: undefined reference to `of_pm_voltdm_notifier_register'
drivers/built-in.o: In function `voltdm_cpufreq_probe':
linux/drivers/cpufreq/cpufreq-voltdm.c:291: undefined reference to `of_pm_voltdm_notifier_register'
linux/drivers/cpufreq/cpufreq-voltdm.c:312: undefined reference to `of_pm_voltdm_notifier_unregister'

Reported-by: Tomi Valkeinen <tomi.valkeinen@ti.com>
Signed-off-by: Nishanth Menon <nm@ti.com>