ARM: Availability of psci_smp_available depends on CONFIG_SMP
Ensure that we can use psci_smp_available without checking for
CONFIG_SMP first (CONFIG_ARM_PSCI=y, CONFIG_SMP=n and
CONFIG_ARCH_TEGRA_124_SOC=y):

|arch/arm/mach-tegra/built-in.o: In function `tegra114_cpuidle_init':
|arch/arm/mach-tegra/cpuidle-tegra114.c:93: undefined reference to `psci_smp_available'
|Makefile:927: recipe for target 'vmlinux' failed

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>