ARM: OMAP: Compile fix OMAP1 DMA V4 Base
When OMAP1, OMAP_DMA4_BASE(DMA V4 Base) is not defined causing
the follow compile error:

arch/arm/plat-omap/dma.c: In function 'omap_set_dma_src_params':
arch/arm/plat-omap/dma.c:273: error: 'OMAP_DMA4_BASE' undeclared (first use in this function)
arch/arm/plat-omap/dma.c:273: error: (Each undeclared identifier is reported only once
arch/arm/plat-omap/dma.c:273: error: for each function it appears in.)
...
make[1]: *** [arch/arm/plat-omap/dma.o] Error 1

Signed-off-by: Ragner Magalhaes <ragner.magalhaes@indt.org.br>
Signed-off-by: Tony Lindgren <tony@atomide.com>