ARM: OMAP2+: Fix amx3_common_pm_in when AM3 is not selected
Move amx3_common_pm_init to pm33xx-core.c from the pm.c common
file.  This fixes a compilation break

arch/arm/mach-omap2/pm.c:290:116: error: redefinition of 'amx3_common_pm_init'
 void __init amx3_common_pm_init(void)
                                                                                                                    ^
In file included from arch/arm/mach-omap2/pm.c:26:0:
arch/arm/mach-omap2/common.h:84:91: note: previous definition of 'amx3_common_pm_init' was here
 static inline void amx3_common_pm_init(void) { }
                                                                                           ^
make[1]: *** [arch/arm/mach-omap2/pm.o] Error 1

When AM3x and AM4x config flags are not enabled

Fixes: 8ecaf7cde ("ARM: OMAP2+: Create dummy platform_device for pm33xx")
Signed-off-by: Dan Murphy <dmurphy@ti.com>
Acked-by: Dave Gerlach <d-gerlach@ti.com>