net: ethernet: ti: cpts: fix allmodconfig build failure
Trivial fix for allmodconfig build failure:
ERROR: "cpts_create" [drivers/net/ethernet/ti/ti_cpsw.ko] undefined!
         ERROR: "cpts_release" [drivers/net/ethernet/ti/ti_cpsw.ko] undefined!
         ERROR: "cpts_create" [drivers/net/ethernet/ti/keystone_netcp_ethss.ko] undefined!
         ERROR: "cpts_release" [drivers/net/ethernet/ti/keystone_netcp_ethss.ko] undefined!
         make[2]: *** [__modpost] Error 1

Fixes: 463ecf4ee876 ("net: ethernet: ti: cpts: rework initialization/deinitialization")
Signed-off-by: Grygorii Strashkn <grygorii.strashko@ti.com>
Signed-off-by: Sekhar Nori <nsekhar@ti.com>