ARM: OMAP: Fix missing channel parameter in omapfb_main.c
Fix missing channel parameter using omap_set_dma_priority() in omapfb_main.c:
drivers/video/omap/omapfb_main.c: In function 'omapfb_do_probe':
drivers/video/omap/omapfb_main.c:1441: error: too few
arguments to function
         'omap_set_dma_priority'

Signed-off-by: Dirk Behme <dirk.behme_at_gmail.com>
Signed-off-by: Tony Lindgren <tony@atomide.com>