mach-types: compile fix: missing MACH_TYPE_OMAP_2430OSK type
Including MACH_TYPE_OMAP_2430OSK missed type.

arch/arm/mach-omap2/board-2430osk.c:134: error: `MACH_TYPE_OMAP_2430OSK' undeclared here (not in a function)
arch/arm/mach-omap2/board-2430osk.c:134: error: initializer element is not constant
arch/arm/mach-omap2/board-2430osk.c:134: error: (near initialization for `__mach_desc_OMAP_2430OSK.nr')

Signed-off-by: Francisco Alecrim <francisco.alecrim@indt.org.br>
Signed-off-by: Tony Lindgren <tony@atomide.com>