remoteproc: fix !CONFIG_OF build breakage
[ Upstream commit 8de3dbd0895bebe52d069a82feae8e3fb51c1bdf ]

Fix this:

drivers/remoteproc/remoteproc_core.c: In function 'rproc_get_by_phandle':
>> drivers/remoteproc/remoteproc_core.c:1167:2: error: implicit declaration of function 'of_find_node_by_phandle' [-Werror=implicit-function-declaration]
     np = of_find_node_by_phandle(phandle);

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: Dave Gerlach <d-gerlach@ti.com>
Cc: Suman Anna <s-anna@ti.com>
Signed-off-by: Ohad Ben-Cohen <ohad@wizery.com>