Revert "arm: omap: perseus: kill compile warning on board-perseus2.c"
This reverts commit 21f70efc436c4e1be0f0b03d9b151ca3e1f607e5.

Compile fails with:

arch/arm/mach-omap1/board-perseus2.c:291: error: invalid operands to binary >> (have 'void *' and 'int')

Signed-off-by: Tony Lindgren <tony@atomide.com>