Revert "ARM: 5794/1: Flush the D-cache during copy_user_highpage()"
This reverts commit 115b22474eb1905da2f606a057da3455833333d3.

Otherwise compile for v7 breaks with:

error: implicit declaration of function '__cpuc_flush_dcache_page'