drm/tidss: Rename dispc_write_irqenable() to dispc_set_irqenable()
The dispc_write_irqenable() function collides with an exported
function of the same name in omapfb. Renaming the function to
dispc_set_irqenable() fixes the following alldefconfig error:

tidss_dispc.c:(.text.dispc_write_irqenable+0x0): multiple definition of `dispc_write_irqenable'
   drivers/video/fbdev/omap2/omapfb/dss/dispc.o:dispc.c:(.text.dispc_write_irqenable+0x0): first defined here

v2: Fix indentation

Fixes: 7bcf7ad9e987 ("drm/tidss: New driver for TI Keystone platform Display SubSystem")
Signed-off-by: Jyri Sarha <jsarha@ti.com>