media: chips-media: wave5: initialize variable
Initialize ret variable in two functions to fix build issue:
 wave5-helper.c:268:6: error: variable 'ret' is used uninitialized
 whenever 'if' condition is false [-Werror,-W sometimes-uninitialized]

Fixes: c08bc57d0e3e ("media: chips-media: wave5: Add Support for Frequency Points")
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>